### ISSUE TITLE
Publication configuration file

### ISSUE THREAD

**Issue by karczewskiPiotr** [karczewskiPiotr/vnlab-tool#3]
## Description
I'd like to start a discussion on how the configuration file for a web publication should look like.
### Content
Things that are for sure relevant:
* Full name of the publication
* Collaborators with roles:
    * programmer
    * editor
* Package manager choice

Maybe it would be a good practice to dump all the preferences, which user chose to create the project, into this file for any future reference on how it was set up? Those could include:
* Any details for `gatsby-config` specified during set up
* Chosen technology extensions

### Format
Should we go for JSON or YAML? Doesn't make much of a difference in my opinion but it's something to choose.

#### JSON
```json
{
  "project_name": "Example project name",
  "collaborators": [
    {
      "github_username": "wuja",
      "role": "programmer"
    },
    {
      "github_username": "john",
      "role": "editor"
    }
  ],
  "pm_preference": "yarn"
}
```
#### YAML
```yaml
project_name: Example project name
collaborators:
  - github_username: wuja
    role: programmer
  - github_username: john
    role: editor
pm_preference: yarn

```

## Correct issue checklist:
- [x] I have added a detailed description
- [ ] I have specified the environment
- [x] I have assigned a Team label (front-end / node / git / design / gatsby)
- [x] I have assigned a Description label (enhancement / bug / etc.)
- [x] I have assigned a Project
- [ ] I have added a Milestone (if applicable)
